config/routes.rb
Slucumber::Application.routes.draw do

  authenticated :client do
    root :to => 'projects#index'
  end
  devise_scope :client do
    root to: 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    get '/settings' => 'devise/registrations#edit'
    delete '/logout' => 'devise/sessions#destroy'
  end
  devise_for :clients , :controllers => { :registrations => 'registrations' }
  resources :projects
resources :actors
resources :initiators
resources :triggers
resources :receivers
resources :responses

  match 'clients' => 'clients#index'
  match 'clients/:id/edit' => 'clients#edit' , :as => :edit_client
  match 'clients/:id' => 'clients#update' , :as => :client

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  # Include default devise modules. Others available are:
  # :timeoutable , :omniauthable , :validatable
  devise :database_authenticatable , :registerable ,
         :recoverable , :rememberable , :trackable ,
         :token_authenticatable , :confirmable , :lockable

  attr_accessible :nick , :password , :password_confirmation , :landmark , :notes
  attr_accessible :remember_me , :email , :unconfirmed_email , :is_admin
  validates_uniqueness_of :nick , { :case_sensitive => false }
  validates_presence_of :nick
  validates_presence_of :password , :password_confirmation , { :on => :create }
  validates_confirmation_of :password
  before_validation do
    # NOTE: we send all confirmation email to our inworld object to relay to the client
    #   but devise requires the email field to change for confirmable and recoverable
    self.nick = self.nick.delete('^A-Za-z0-9 .').gsub(' ' , '.') unless self.nick.nil?
    self.email = self.unconfirmed_email = self.nick + BOGUS_EMAIL unless self.nick.blank?
    self.landmark ||= "" ; self.notes ||= "" ;
  end

  def admin ; Client.find_by_nick 'me' ; end ;

  module Devise::Models::Confirmable
    def send_on_create_confirmation_instructions # on create
      SlMailer.sl_email(self).deliver
    end

    def send_confirmation_instructions # on update
      self.confirmation_token = nil if reconfirmation_required?
      @reconfirmation_required = false
      generate_confirmation_token! if self.confirmation_token.blank?
      SlMailer.sl_email(self).deliver
    end
  end


  def self.display_clients(current_client) # clientLoginTd styling
    clients = [] ; display_nicks = [] ; longest_named_client = nil ; longest = 0 ;
    self.all.each do | client | ; next if client == current_client ;
      curr_nick = client.email.split('@').first ; new_nick = client.nick ;
      display_nick = (new_nick == curr_nick)? curr_nick : curr_nick + " (" + new_nick + ")"
      clients << client ; display_nicks << display_nick ; n_chars = display_nick.size ;
      longest_named_client = client and longest = n_chars if n_chars > longest ;
    end
    [clients , display_nicks , longest_named_client]
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_client!
  before_filter { redirect_to root_path unless current_client.is_admin }

  def index
    @clients , @display_nicks , @longest_named_client = Client.display_clients(current_client)

    respond_to { | format | ; format.html }
  end

  def edit ; @client = Client.find(params[:id]) ; respond_to { | format | ; format.html } ; end ;

  def update
    @client = Client.find(params[:id])

    respond_to do | format |
      format.html do
        if params[:commit] == "Back"
          redirect_to clients_url
        elsif params[:commit] == "Destroy " + @client.nick ; @client.destroy ;
          redirect_to clients_url , :notice => "Client was successfully destroyed."
        elsif @client.update_attributes(params[:client])
          redirect_to edit_client_url(@client) , :notice => "Client was successfully updated."
        else
          render action: "edit"
        end
      end
    end
  end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/edit.html.erb
<h2 id="clientH2"><%= @client.nick %><br /></h2>

<%= form_for(@client) do | client_form | %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being updated:</h2>
      <ul><% @client.errors.full_messages.each do | msg | %><li><%= msg %></li><% end %></ul>
    </div>
  <% end %>

  <div id="adminEditClientBtns" class="actions">
    <%= client_form.submit %>
    <%= submit_tag "Destroy #{@client.nick}" , { :confirm => "return confirm('Are you sure?')" } %>
    <%= submit_tag "Back" %>
  </div>
  <table id="adminEditClientTable" class="field">
    <tr>
      <td><%= client_form.label :nick %><%= client_form.text_field :nick , { :disabled => true } %></td>
      <td><%= client_form.label :landmark %><%= client_form.text_field :landmark %></td>
      <td>Admin?<%= client_form.check_box :is_admin %></td>
      <td id="adminEditClientPadTd">&nbsp;</td>
    </tr>
    <th colspan="4"><%= client_form.label :notes %></th>
    <tr><td colspan="4"><%= client_form.text_area :notes , { :autofocus => true } %></td></tr>
  </table>
<% end %>

<p></p>

<h2 id="projectsH2"><b><%= @client.projects.size.to_s %> Projects</b></h2>
<table id="adminClientProjectsTable">
  <% unless @client.projects.size.zero? %>
    <th id="projectsNameTh"><b>Project name:</b></td>
    <th id="projectsDestroyTh"></th>
    <th id="projectsDescriptionTh"><b>Description:</b></td>
  <% end %>
  <% @client.projects.each do | project | %>
    <tr>
      <td><%= button_to ("#{project.name} (#{project.id})"), project_path(project) , :method => :get %></td>
      <td><%= button_to "Destroy " + project.name , project , { :onclick => "return confirm('Are you sure?')" , :method => :delete  } %></td>
      <td><%= project.desc %></td>
    </tr>
  <% end %>
</table>

app/views/clients/index.html.erb
<h2 id="clientsH2">Clients</h2>

<table id="clientsTable">
  <th id="clientLoginTh">Nick</th>
  <th id="clientLandmarkTh">Landmark</th>
  <th id="clientNProjectsTh"># Projects</th>
  <th id="clientNotesTh">Notes</th>
  <% @clients.each_with_index do | client , i | %>
    <tr>
      <td class="clientLoginTd">
        <% css_class = (client.is_admin)? 'adminLogin' : '' %>
        <% css_class = css_class + ' fillTd' unless client === @longest_named_client %>
        <%= button_to ("#{@display_nicks[i]} (#{client.id})") , edit_client_url(client) , { :class => css_class.lstrip , :method => :get } %>
      </td>
      <td class="clientLandmarkTd">
        <% landmark_btn = button_to client.landmark , client.landmark , { :method => :get } %>
        <%= (client.landmark.empty?)? '' : landmark_btn %>
      </td>
      <td class="clientNProjectsTd"><%= client.projects.size.to_s + " Projects" %></td>
      <td class="clientNotesTd"><%= client.notes %></td>
    </tr>
  <% end %>
</table>