config/routes.rb
Slucumber::Application.routes.draw do

  authenticated :client do
    root :to => 'projects#index'
  end
  devise_scope :client do
    root to: 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    get '/settings' => 'devise/registrations#edit'
    delete '/logout' => 'devise/sessions#destroy'
  end
  devise_for :clients , :controllers => { :registrations => 'registrations' }
  resources :projects
resources :actors
resources :initiators
resources :triggers
resources :receivers
resources :responses

  match 'clients' => 'clients#index'
  match 'clients/:id/edit' => 'clients#edit' , :as => :edit_client
  match 'clients/:id' => 'clients#update' , :as => :client

end

app/models/project.rb
class Project < ActiveRecord::Base
def dbgactors(sender)
p sender + ((self.events.first.initiator.nil?)? "nil" : self.events.first.initiator.id.to_s)
end
def dbgevents(sender)
p sender + ((self.events.nil?)? "nil" : self.events.size.to_s)
end

  belongs_to :client
  has_many :events
  accepts_nested_attributes_for :events , :allow_destroy => true
  attr_accessible :name , :desc , :notes , :client_id , :events_attributes
  validates_presence_of :name , :client_id
  before_validation { self.desc ||= "" ; self.notes ||= "" }
=begin
  before_create {
p "event.rb before_create  IN n_events=" + ((self.events)? self.events.size.to_s : "events nil")
    self.events.create() ;
p "event.rb OUT n_events=" + ((self.events)? self.events.size.to_s : "events nil")
  }
=end
  after_create {
dbgevents "project.rb after_create  IN n_events=" #; return if true ;
#    an_event = self.events.create() ;
    self.events.build() ; return if self.events.size.zero? ;
#self.events.first.build_initiator() ; self.events.first.build_trigger() ;
#self.events.first.build_receiver() ; self.events.first.build_response() ;
#self.events.first.self.save
=begin
self.events.build_initiator({}) ; self.events.build_trigger({}) ;
self.events.build_receiver({}) ; self.events.build_response({}) ;
self.save
=end
#dbgactors "project.rb after_create initiator    ="
    self.save
#dbgactors "project.rb after_create initiator OUT="
dbgevents "project.rb after_create OUT n_events="
  }


  def admin? ; self.is_admin ; end ;

  def self.form_remote? ; true ; end ;

  def self.display_projects(projects) # projectNameTd styling
    longest_name = "" ; longest = 0 ;
    projects.each do | project |
      name = project.name ; n_chars = name.size ;
      longest_name = name and longest = n_chars if n_chars > longest ;
    end
    longest_name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_client!
  before_filter { @admin = current_client.is_admin }  
#  before_filter :admin_index , :only => :index
#  def admin_index ; redirect_to clients_path if current_client.is_admin ; end ;
#  def admin_destroy ; redirect_to edit_client_path @project.client_id if @admin ; end ;

  def index
    redirect_to clients_path and return if @admin

    @projects = Project.where("client_id = ?" , current_client)
    @longest_name = Project.display_projects(@projects)

    respond_to do | format |
      format.html
    end
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def create
#    @project = Client.find(current_client.id).projects.build(params[:project])
    @project = current_client.projects.build(params[:project])

    respond_to do |format|
      if params[:commit] == "Cancel"
        format.html { redirect_to projects_path }
        format.json { head :no_content }
      elsif Project.find_by_name(params[:project][:name])
        format.html { render action: "new"  , :status => "Project already exists with that name" }
        format.json { render :json => @project.errors , :status => "Project already exists with that name" }
      elsif @project.save
        format.html { redirect_to edit_project_url(@project) , :notice => "Project was successfully created." }
        format.json { render :json => @project , :status => :created , :location => @project }
      else
        format.html { render action: "new" }
        format.json { render :json => @project.errors , :status => :unprocessable_entity }
      end
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

def my_ajax
=begin
  @actor = nil ;
  (@actor.save && (render { :partial => "actor" , :object => @actor })) if params[:id] &&
      (@actor = Actor.find(params[:id])) &&
      ((params[:option] && (@actor.option = params[:option])) or
      (params[:name] && (@actor.name = params[:name])) or
      (params[:data] && (@actor.name = params[:data])))
=end
=begin
    @actor = Actor.find(params[:id])
    @actor.option = params[:option] if params[:option]
    @actor.name = params[:name] if params[:name]
    @actor.data = params[:data] if params[:data]
    @action.save ; render :partial => "actor" , :object => @actor
=end
end

  def edit
    @project = Project.find(params[:id])
print "\n\n\n\n\nprojects::edit n_events=" + ((@project.events.nil?)? "events=nil" : @project.events.size.to_s + "\n")

@initiators = {} ; @triggers = {} ; @receivers = {} ; @responses = {} ;
    @project.events.each do | event |
=begin
@initiators[event] = Actorevent.initiator_id
@triggers[event] = Trigger.find event.trigger_id
@receivers[event] = Receiver.find event.receiver_id
@responses[event] = Response.find event.response_id
=end
#@initiator = Actor.find(event.initiator_id)
#event.find(event.initiator_id)
@initiators[event] = event.initiator ; @triggers[event] = event.trigger ;
@receivers[event] = event.receiver ; @responses[event] = event.response ;
#p "projects::edit id=" + event.id.to_s + " initiator=" + @initiators[event].id.to_s + " trigger=" + @triggers[event].id.to_s + " receiver=" + @receivers[event].id.to_s + " response=" + @responses[event].id.to_s
#p "projects::edit initiator.id=" + Actor.find(event.initiator.id).to_s ; p "project::edit trigger.id=" + Actor.find(event.trigger_id).to_s ; p "project::edit receiver.id=" + Actor.find(event.receiver_id).to_s ; p "project::edit response.id=" + Actor.find(event.response_id).to_s
    end

    respond_to do |format|
      format.html # .html.rb
      format.json { render json: @project }
    end

=begin
    respond_to do | format |
      if params[:commit] == "Cancel"
        format.html { redirect_to projects_path }
        format.json { head :no_content }
<%= text_field_tag customer , :name %> # Create a partial _customer.
<%= text_field_tag customer , :address %> # Create a partial _customer.
<% form_for @customer do | f | %> # Then in say your new view
   <%= render :partial=>"customer", :object=>@customer %>
   <%= f.submit_tag "Create" %>
=end
=begin
<% form_for :customer, @customer, :url => { :controller => "customers", :action => "editCustomer", :remote=> true } do |f| %>
  <%= render :partial=>"customers/customer", :object=>@customer %>
  <%= f.submit 'Save' %>
<% end %> # And my form_for

<div> # And my partial
  <%= text_field_tag customer, :name %>
  <%= text_field_tag customer, :kurz %>
  <%= text_field_tag customer, :info %>
  <%= text_field_tag customer, :strasse %>
  <%= text_field_tag customer, :plz %>
  <%= text_field_tag customer, :ort %>
  <%= text_field_tag customer, :tel %>
  <%= text_field_tag customer, :fax %>
  <%= text_field_tag customer, :mail %>
  <%= text_field_tag customer, :www%>
</div>
=end

=begin
remote_function(  :url => { :action => 'editCustomer',
                            :controller => 'customers'},
                            :with => "'id=' +$('specificCustomers').value");%>
=end
  end
def dbg_events
  dbg = " n_projects=" + Project.count.size.to_s + " n_events=" + @project.events.size.to_s + " [ "
  @project.events.each { | ev | dbg += ev.id.to_s + " , " } ; dbg + " ]" ;
end ;

  def update
    @project = Project.find(params[:id])
print "\n\n\n\nProjects>>update params[:commit]=" + params[:commit].to_s + " project.id=" + params[:id].to_s + "\n"

    if params[:commit] == "Cancel"
      respond_to do | format |
        format.html { redirect_to projects_path }
        format.json { head :no_content }
      end
    elsif params[:commit] == "Save" || true # && @project.update_attributes(params[:project])
p "Projects>>update update_attributes  IN=" + dbg_events ; first = @project.events.first ;
      if @project.update_attributes(params[:project])
p "Projects>>update update_attributes OUT=" + dbg_events + " Project update ok"
        @partial = (render :partial => 'events_form' , :object => @project).first.to_s
print "\nProjects>>update @partial=\n" + @partial + "\n"
#print "\nProjects>>update @partial=\n" + @partial[0..30] + "\n"
#tag_btn_text = "1234567890" ; @partial.gsub!(">#{tag_btn_text}<" , ">CLOBBERED<") ;
        respond_to do | format |
          format.json { @partial }
          format.html { raise "wtf" }
        end
      else
p "Projects>>update update_attributes OUT=" + dbg_events + " Project update fail."
        respond_to do | format |
          format.html { render action: "edit" }
          format.json {}
        end
      end
    else
p "Projects>>update update_attributes OUT=" + dbg_events + " Project update invalid"
      format.html { redirect_to edit_project_path(@project) , { :notice => "Project was successfully updated." } }
      format.json { head :no_content }
    end
  end
=begin
  def update
    @project = Project.find(params[:id])
print "\n\n\n\nProjects>>update params[:commit]=" + params[:commit].to_s + " project.id=" + params[:id].to_s + "\n"

    respond_to do | format |
      if params[:commit] == "Cancel"
        format.html { redirect_to projects_path }
        format.json { head :no_content }
#      elsif params[:commit] == "Save" && @project.update_attributes(params[:project])
      elsif params[:commit] == "Save" || true
p "Projects>>update update_attributes  IN=" + dbg_events ; first = @project.events.first ;
#(p "Projects>>update update_attributes first initiator  IN=" + first.initiator.id.to_s + " trigger="  + first.trigger.id.to_s + " receiver="  + first.receiver.id.to_s + " response="  + first.response.id.to_s) unless first.nil? || first.id.nil?
        if @project.update_attributes(params[:project])
#p "Projects>>update update_attributes OUT=" + dbg_events
#(p "Projects>>update update_attributes first initiator OUT=" + first.initiator.id.to_s + " trigger="  + first.trigger.id.to_s + " receiver="  + first.receiver.id.to_s + " response="  + first.response.id.to_s) unless first.nil? || first.id.nil?
#@project.events.first.trigger.data = ":)" ; @project.save ;

# NOTE: rend = (render :html => { :partial => 'events_form' , :object => @project })
#rend = (render :action => :edit , :format => :html)
#p "rend.class=" + rend.class.to_s + " rend.first.class=" + rend.first.class.to_s ;
#=begin
id = @project.id.to_s
@partial = (render :html => { :partial => 'events_form' , :object => @project }).first.to_s
#@partial = (render :action => :edit , :format => :html).first.to_s
#@partial = (render :action => :update , :format => :html).to_s
#@partial = (render 'projects/events_form').first.to_s
print "\nProjects>>update update_attributes @partial=\n" + @partial + "\n"
@partial.gsub!(">1234567890<" , ">YAY<")
#=end
#          format.html { redirect_to edit_project_path(@project) , { :notice => 'Project was successfully updated.' } }
#          format.json { 'console.log("' + (render "events_form") + '") ;' }
          format.json {}
#format.html { render :partial => 'events_form' , :object => @project ; return ; }
#format.html { raise "wtf" }
#          format.json { render :json => 'document.getElementById("edit_project_' + @project.id.to_s + '").innerHTML = "' + @partial + '" ;'; }
#          format.json { render :json => 'console.log("' + (render @project) + '");' }
#          format.json { render :json => 'console.log("' + @partial + '");' }
#          format.html { render action: "edit" }
#          format.json { 'renderEventsForm(' + @project.id.to_s + ' , "' + (render :action => :edit) + '") ;' }
          #format.json { 'renderEventsForm(' + id + ' , "' + partial + '") ;' }

# format.json {
# p "Projects>>update json id=" + id
# '$("#" + "events_form_" + id).replaceWith("' + (render :json => { :partial => 'events_form' , :object => @project }).first + '") ;'

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_actor_fields.html.erb
<fieldset>
<% p "_actor_fields.html.erb actor_key nil" unless ACTOR_MAP.keys.include? actor_key %>
  <% return unless ACTOR_MAP.keys.include? actor_key %>

<% p "_actor_fields.html.erb actor=" + actor_key.to_s %>
  <% actor_map = ACTOR_MAP[actor_key] %>
  <% label = actor_map[:label] %>
  <% options = actor_map[:options][:default] %>
<% p "_actor_fields.html.erb actor_map=" + actor_map.class.to_s + " label=" + label + " options=" + options.to_s %>

  <% trace_js = 'console.log("_actor_fields.html.erb onchange actor_key=' + actor_key.to_s + ' ok=" + this + "::" + this.value) ;' %>
  <% submit_js = 'submitNestedForm() ;' %>
  <% onchange_js = trace_js + submit_js %>

  <legend style="padding: 0.0em 0.2em ;"><%= label %></legend>

  <div><%= event_builder.select :kind , options , {} , { :onchange => onchange_js } %></div>

  <div class="hiddenXXX"><%= event_builder.text_field :data , { :onchange => onchange_js } %></div>
</fieldset>

app/views/projects/_events_form.html.erb
<!-- < % = nested_form_for @project , :remote => true , :html => { 'data-type' => 'script' } do | project_form | % > -->
<%= nested_form_for @project , :remote => true do | project_form | %>
  <div id="projectEditBtnsDiv" class="actions">
    <%= submit_tag "Cancel" %>
    <%= project_form.submit %>
  </div>

  <table id="project_events">
    <th>+-</th><th>Tag:</th><th>Initiator:</th><th>Trigger:</th><th>Receiver:</th><th>Response:</th>
<% n = 0 ; print "\nproject (" + n.to_s + ")\n" %>
    <%= project_form.fields_for :events , :wrapper => false do | event_builder | %>
<% print "\nevent (" + (n = n + 1).to_s + ")\n" %>
      <% event = event_builder.object %>

      <tr class="fields projectEventTr">
<% print "\n\"_events_form.html.rb event.id='" + ((event)? event.id.to_s + "' new_record?=" + event.new_record?.to_s : "nil'") + "\"\n" %>
<% p "_events_form.html.rb " + event.initiator.class.to_s + ".event_id=" + ((event && event.initiator)? event.initiator.event_id.to_s : "nil") %>
<% p "_events_form.html.rb event.notes=" + event.notes.to_s + ((event.notes)? event.notes.size.to_s : 'nil') %>
<% p "_events_form.html.rb event.valid?=" + event.valid?.to_s %>
<% actor = nil %>
<% if false %>
<% initiator = event.initiator %>
<% trigger = event.trigger %>
<% receiver = event.receiver %>
<% response = event.response %>
<% elsif false %>
<% initiator = event.build_initiator() %>
<% trigger = event.build_trigger() %>
<% receiver = event.build_receiver() %>
<% response = event.build_response() %>
<% elsif true %>
<% initiator = event.initiator ||= event.build_initiator() %>
<% trigger = event.trigger ||= event.build_trigger() %>
<% receiver = event.receiver ||= event.build_receiver() %>
<% response = event.response ||= event.build_response() %>
<% elsif false %>
<% event.tag = 'Tag:' if event.tag.blank? %>
<% initiator = event.initiator ||= Initiator.new() %>
<% trigger = event.trigger ||= Trigger.new() %>
<% receiver = event.receiver ||= Receiver.new() %>
<% response = event.response ||= Response.new() %>
<% p "_events_form.html.rb Initiator.new.valid?=" + initiator.valid?.to_s %>
<% end %>
<% p "_events_form.html.rb initiator=" + ((initiator.nil?)? 'nil' : initiator.id.to_s) + " trigger=" + ((trigger.nil?)? 'nil' : trigger.id.to_s) + " receiver=" + ((receiver.nil?)? 'nil' : receiver.id.to_s) + " response=" + ((response.nil?)? 'nil' : response.id.to_s) %>

        <td class="projectEventRemoveTd">
          <%= event_builder.hidden_field :id %> <!-- table must include this somewhere -->
          <%= event_builder.link_to_remove(:class => "remove_event" , :href => "#" , :confirm => "Are you sure?") do %>
            <% btn = "X" + ((current_client.is_admin && event.id)? " (" + event.id.to_s + ")" : "") %>
            <%= button_tag btn , :type => 'button' %><% end %></td>

        <td class="projectEventTagTd">
          <% toggle_js = 'toggleTagInput(this) ;' ; submit_js = 'submitNestedForm() ;' ; %>
          <% onTagTextChange = (onTagBtnClick = toggle_js) + submit_js ; %>
          <div class="eventTagTextDiv"><%= event_builder.text_field :tag , { :onchange => onTagTextChange } %></div>
          <div class="eventTagBtnDiv"><%= button_tag event.tag , { :type => 'button' , :onclick => onTagBtnClick } %></div>
          <div class="eventNotesDiv"><%= event_builder.text_field :notes , { :onchange => onTagTextChange } %></div></td>
        <td class="projectEventInitiatorTd">
          <%= event_builder.fields_for :initiator , :wrapper => false do | initiator_builder | %>
            <%= render 'actor_fields' , :event_builder => initiator_builder , :actor_key => :initiators %>
          <% end %></td>
        <td class="projectEventTriggerTd">
            <%= event_builder.fields_for :trigger , :wrapper => false do | trigger_builder | %>
            <%= render 'actor_fields' , :event_builder => trigger_builder , :actor_key => :triggers %>
          <% end %></td>
        <td class="projectEventReceiverTd">
          <%= event_builder.fields_for :receiver , :wrapper => false  do | receiver_builder | %>
            <%= render 'actor_fields' , :event_builder => receiver_builder , :actor_key => :receivers %>
          <% end %></td>
        <td class="projectEventResponseTd">
          <%= event_builder.fields_for :response , :wrapper => false do | response_builder| %>
            <%= render 'actor_fields' , :event_builder => response_builder , :actor_key => :responses %>
          <% end %></td>
      </tr>
    <% end %>

    <tr><td><%= project_form.link_to_add :events , :class => "add_nested_fields" do %>
      <%= button_tag "+" , :type => 'button' %><% end %></td>
      <td></td><td></td><td></td><td></td><td></td>
    </tr>
  </table>

  <div class="field">Notes:<br /><%= project_form.text_area :notes %></div>

<% end %>

app/views/projects/_events_form3.html.erb
<%= nested_form_for @project , :remote => true , :html => { 'data-type' => 'script' } do | project_form | %>

  <div id="projectEditBtnsDiv" class="actions">
    <%= submit_tag "Cancel" %>
    <%= project_form.submit %>
  </div>

  <div id="projectEventsDiv">
<% n = 0 ; print "\nproject (" + n.to_s + ")\n" %>
    <%= project_form.fields_for :events , :wrapper => false do | event_builder | %>
<% print "\nevent (" + (n = n + 1).to_s + ")\n" %>
      <% event = event_builder.object %>

    <table id="project_events">
      <tr class="projectEventSpacerTr">
        <td class="projectEventRemoveTd" colspan="4">
          <%= event_builder.hidden_field :id %> <!-- table must include this somewhere -->
          <%= event_builder.link_to_remove(:class => "remove_event" , :href => "#" , :confirm => "Are you sure?") do %>
            <% btn = "X" + ((current_client.is_admin && event.id)? " (" + event.id.to_s + ")" : "") %>
            <%= button_tag btn , :type => 'button' %><% end %>
          <% onchange = "
              var tagTextDiv = this.parentNode ;
              var tagBtnDiv = tagTextDiv.parentNode.children[1] ;
              var tagBtn = tagBtnDiv.children[0] ;
console.log('this.id=' + tagBtn.innerHTML) ;
              tagBtn.innerHTML = this.value ;
              tagTextDiv.style.display = 'none' ;
              tagBtnDiv.style.display = 'block' ;" %>
          <% onclick = "
              var tagBtnDiv = this.parentNode ;
              var tagTextDiv = tagBtnDiv.parentNode.children[0] ;
              tagBtnDiv.style.display = 'none' ;
              tagTextDiv.style.display = 'block' ;" %>
          <span class="eventTagTextDiv"><%= event_builder.text_field :tag , { :onchange => onchange } %></span>
          <span class="eventTagBtnDiv"><%= button_tag event.tag , { :type => 'button' , :onclick => onclick } %></span>
          <%= event_builder.text_field :notes %></td></tr>

      <tr class="fields projectEventTr">
<% print "\n\"_events_form.html.rb event.id='" + ((event)? event.id.to_s + "' new_record?=" + event.new_record?.to_s : "nil'") + "\"\n" %>
<% p "_events_form.html.rb " + event.initiator.class.to_s + ".event_id=" + ((event && event.initiator)? event.initiator.event_id.to_s : "nil") %>
<% p "_events_form.html.rb event.notes=" + event.notes.to_s + ((event.notes)? event.notes.size.to_s : 'nil') %>
<% p "_events_form.html.rb event.valid?=" + event.valid?.to_s %>
<% actor = nil %>
<% if false %>
<% initiator = event.initiator %>
<% trigger = event.trigger %>
<% receiver = event.receiver %>
<% response = event.response %>
<% elsif false %>
<% initiator = event.build_initiator() %>
<% trigger = event.build_trigger() %>
<% receiver = event.build_receiver() %>
<% response = event.build_response() %>
<% elsif true %>
<% initiator = event.initiator ||= event.build_initiator() %>
<% trigger = event.trigger ||= event.build_trigger() %>
<% receiver = event.receiver ||= event.build_receiver() %>
<% response = event.response ||= event.build_response() %>
<% elsif false %>
<% event.tag = 'Tag:' if event.tag.blank? %>
<% initiator = event.initiator ||= Initiator.new() %>
<% trigger = event.trigger ||= Trigger.new() %>
<% receiver = event.receiver ||= Receiver.new() %>
<% response = event.response ||= Response.new() %>
<% p "_events_form.html.rb Initiator.new.valid?=" + initiator.valid?.to_s %>
<% end %>
<% p "_events_form.html.rb initiator=" + ((initiator.nil?)? 'nil' : initiator.id.to_s) + " trigger=" + ((trigger.nil?)? 'nil' : trigger.id.to_s) + " receiver=" + ((receiver.nil?)? 'nil' : receiver.id.to_s) + " response=" + ((response.nil?)? 'nil' : response.id.to_s) %>

        <td class="projectEventInitiatorTd">
  <% (actor = initiator) %>
  <%= event_builder.fields_for :initiator , :wrapper => false do | initiator_builder | %>
    <%= render 'actor_fields' , :event_builder => initiator_builder , :actor_class => 'Initiator' %>
  <% end %>
        </td>
        <td class="projectEventTriggerTd">
  <% (actor = trigger) %>
  <%= event_builder.fields_for :trigger , :wrapper => false do | trigger_builder | %>
    <%= render 'actor_fields' , :event_builder => trigger_builder , :actor_class => 'Trigger' %>
  <% end %>
          </td>
        <td class="projectEventReceiverTd">
  <% (actor = receiver) %>
  <%= event_builder.fields_for :receiver , :wrapper => false  do | receiver_builder | %>
    <%= render 'actor_fields' , :event_builder => receiver_builder , :actor_class => 'Receiver' %>
  <% end %>
          </td>
        <td class="projectEventResponseTd">
  <% (actor = response) %>
  <%= event_builder.fields_for :response , :wrapper => false do | response_builder| %>
    <%= render 'actor_fields' , :event_builder => response_builder , :actor_class => 'Response' %>
  <% end %>
        </td>
      </tr>
    <% end %>

    <tr><td><%= project_form.link_to_add :events , :class => "add_nested_fields" do %>
      <%= button_tag "+" , :type => 'button' %><% end %></td>
      <td></td><td></td><td></td><td></td><td></td>
    </tr>
  </table>
</div>
  <div class="field">Notes:<br /><%= project_form.text_area :notes %></div>

<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do | project_form | %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul><% @project.errors.full_messages.each do | msg | %><li><%= msg %></li><% end %></ul>
    </div>
  <% end %>

  <div class="actions">
    <%= button_tag "Cancel" , :type => 'button' , :onclick => "location.href = '#{projects_path}'" %>
    <%= project_form.submit %>
  </div>
  <div class="field">
    <%= project_form.label :name %><br />
    <%= project_form.text_field :name , :autofocus => true %>
  </div>
  <div class="field">
    <%= project_form.label :desc %><br />
    <%= project_form.text_field :desc %>
  </div>
  <div class="field">
    <%= project_form.label :notes %><br />
    <%= project_form.text_area  :notes %>
  </div>
<% end %>

app/views/projects/_project.html.erb
hello

app/views/projects/_project.js.erb
alert('_project.js.erb') ;

app/views/projects/actor.remote.js.erb
../actors/actor.remote.js.erb

app/views/projects/edit.html.erb
<div id="projectFormDiv"><%= render 'events_form' %></div>

<script type="text/javascript">
window.NestedFormEvents.prototype.insertFields = function(content, assoc, link)
  { return $(content).insertBefore($(link).closest('tr')) ; }
</script>

app/views/projects/edit.js.erb
// "app/views/actors/edit.js.erb"

var formId = "<%=j (form_id = 'edit_project_' + @project.id.to_s) %>" ;
<% print "\nedit.js.herb form_id=" + form_id + "\n" %>

var theForm = document.getElementById(formId) ;
console.log("edit.js.erb formId=" + formId + " theForm=" + theForm) ;
//console.log("edit.js.erb theForm.innerHTML=" + theForm.innerHTML) ;
var project = "<%=j (@project)? @project.name : 'nil' %>" ;
console.log("edit.js.erb @project.name=" + project) ;
console.log("edit.js.erb @partial=<%= @partial %>") ;

//theForm.innerHTML = "< % =j @partial % >" ;
//console.log("edit.js.erb theForm.parentNode=" + theForm.parentNode) ;
//var parentInnerHTML = theForm.parentNode.innerHTML ;
//theForm.parentNode.innerHTML = "<%= escape_javascript @partial %>" ;
//console.log("changed?=" + (parentInnerHTML != theForm.parentNode.innerHTML)) ;
//theForm.innerHTML("< % = escape_javascript(render :partial => 'projects/events_form') % >") ;

app/views/projects/index.html.erb
<h2 id="projectsH2">My Slucumber Projects</h2>

<table id="projectsTable">
  <% is_new_name_longest = (new_name = "Create New Project").size > @longest_name.size %>
  <% @longest_name = new_name if is_new_name_longest %>
  <% btn_params = { :class => ((is_new_name_longest)? '' : 'fillTd') , :method => :get } %>
  <tr><td><%= button_to new_name , new_project_path , btn_params %></td><td></td><td></td><td></td></tr>
  <% @projects.each do | project | %>
    <tr>
      <td class="projectNameTd">
        <% css_class = ((project.name == @longest_name)? '' : 'fillTd') %>
        <%= button_to project.name , project , { :class => css_class , :method => :get } %>
      </td>

      <td class="adminProjectIdTd"><%= (current_client.is_admin)? "(" + project.id.to_s + ")" : "" %></td>
      <td class="projectDescTd"><%= project.desc %></td>
      <td><%= button_to "Update" , edit_project_path(project) , :method => :get %></td>
      <td><%= button_to "Destroy" , project , { :onclick => "return confirm('Are you sure?')" , :method => :delete  } %></td>
    </tr>
  <% end %>
</table>