config/routes.rb
Slucumber::Application.routes.draw do

  authenticated :client do
    root :to => 'projects#index'
  end
  devise_scope :client do
    root to: 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    get '/settings' => 'devise/registrations#edit'
    delete '/logout' => 'devise/sessions#destroy'
  end
  devise_for :clients , :controllers => { :registrations => 'registrations' }
  resources :projects
resources :actors
resources :initiators
resources :triggers
resources :receivers
resources :responses

  match 'clients' => 'clients#index'
  match 'clients/:id/edit' => 'clients#edit' , :as => :edit_client
  match 'clients/:id' => 'clients#update' , :as => :client

end

app/views/layouts/_header.html.erb
<table id="headerTable">
  <tr>
    <td id="messagesTd"><%= render 'layouts/messages' %></td>
    <td id="siteTitleTd">Slucumber</td>
    <td id="loginTd">
      <% if client_signed_in? %>
        <% admin = current_client.is_admin %>
        <% nick = current_client.nick.gsub('.' , ' ') %>
        <% login_css_id = (admin)? 'adminLoginSpan' : 'clientLoginSpan' %>
        <% client = nil ; link_text = current_data = "" ; %>

        <% if admin %>
          <% if @project %>
            <% client = @project.client %>
            <% link_text = "Edit #{client.nick}" ; path = edit_client_path client ; %>
            <% current_data = "#{@project.name} (#{@project.id})" %>
          <% elsif @client %>
            <% client = @client %>
            <% link_text = 'Clients' ; path = clients_path ; %>
            <% current_data = "#{@client.nick} (#{@client.id})" %>
          <% end %>
        <% elsif @project %>
            <% link_text = 'My Projects' ; path = projects_path ; %>
            <% current_data = @project.name %>
        <% end %>

        <span id="navSpan">
          <%= ((current_data.nil?)? "" : current_data) %>
          <%= link_to link_text , path unless path.nil? %>
          <%= (admin && client)? " (#{client.id})" : "" %></span>
        <span id="loginSpan">
          <span id="<%= login_css_id %>"><%= nick %></span>
          <%= link_to 'Settings' , '/settings' %>
          <%= link_to('Logout' , '/logout' , :method => :delete) %>
        </span>
      <% else %>
        <span id="loginSpan">
          <%= link_to('Login' , '/login') %><%= link_to 'Sign up' , '/signup' %>
        </span>
      <% end %>
    </td>
  </tr>
</table>

app/views/layouts/_header.html.ok.erb
<table id="headerTable">
  <tr>
    <td id="messagesTd"><%= render 'layouts/messages' %></td>
    <td id="siteTitleTd">Slucumber</td>
    <td id="loginTd">
      <% if client_signed_in? %>
        <% nick = current_client.nick.gsub('.' , ' ') %>
        <% admin = current_client.is_admin %>
        <% if @project %>
          <span class="projectName"><%= @project.name + ((admin)? " (#{@project.id})" : "") %></span>
        <% elsif @client && @client == current_client %>
          <span class="clientName">(<%= @client.id %>)</span>
        <% elsif @client && @client != current_client && admin %>
          <span class="clientName"><%= @client.nick %></span>
        <% end %>
        <% css_class = (admin)? 'adminLoginSpan' : 'clientLoginSpan' %>
        <span class="<% css_class %>"><%= nick %></span>
        <%= link_to 'My Projects' , '/projects' %>
        <%= link_to 'Settings' , '/settings' %>
        <%= link_to('Logout' , '/logout' , :method => :delete) %>
      <% else %>
        <%= link_to('Login' , '/login') %>
        <%= link_to 'Sign up' , '/signup' %>
      <% end %>
    </td>
  </tr>
</table>

app/views/layouts/_messages.html.erb
<div id="messages">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width , initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Slucumber" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Slucumber" %>">
    <%= stylesheet_link_tag "application" , :media => "all" %>
    <%= javascript_include_tag "application" %>
<!-- < % = javascript_include_tag :defaults % > -->
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">

      <header>
        <%= render 'layouts/header' %>
        <% render 'layouts/messages' %>
      </header>

      <div id="main" role="main"><%= yield %></div>

      <footer></footer>

    </div>
  </body>
</html>